from enum import StrEnum


class SignalCode(StrEnum):
    URGENCY = "URGENCY"
    LINK_REQUEST = "LINK_REQUEST"
    IDENTITY_VERIFICATION = "IDENTITY_VERIFICATION"
    BANK_IMPERSONATION = "BANK_IMPERSONATION"
    GOVERNMENT_IMPERSONATION = "GOVERNMENT_IMPERSONATION"
    OTP_REQUEST = "OTP_REQUEST"
    CREDENTIAL_REQUEST = "CREDENTIAL_REQUEST"
    REMOTE_ACCESS = "REMOTE_ACCESS"
    PAYMENT_REQUEST = "PAYMENT_REQUEST"
    ACCOUNT_THREAT = "ACCOUNT_THREAT"
    INVESTMENT_PROMISE = "INVESTMENT_PROMISE"
